### ISSUE TITLE
NEWSLETTER 

### ISSUE THREAD

**Issue by Mohammed-Taysser** [Mohammed-Taysser/Gutenberry#11]
NEWSLETTER  button is not justify

**Comment by AsfandToor** [comment]
Can you send me a screenshot of  where the issue is?. I might be able to help.

**Comment by Mohammed-Taysser** [comment]
Hi friend, I just test my design and learn how to make issue and other thing on GitHub 😄  😃 
I build the website in Linux which has different look on window, and now it's more different from what I expect

like this screen in [home page](https://mohammed-taysser.github.io/Gutenberry/index.html)
![newsletter](https://user-images.githubusercontent.com/62953174/134340093-7bc14784-d5ed-40d5-8423-12fb657d1445.PNG)

for solve in temporary, I just use `top: 6px;`

**Comment by AsfandToor** [comment]
Hi! Very Well I understand the problem and will fix it for you.

**Comment by Mohammed-Taysser** [comment]
This will be kind of you

**Comment by AsfandToor** [comment]
I have solved it I will create the pull request. Sorry for the delay

**Comment by Mohammed-Taysser** [comment]
Amazing friend, sorry for your time, and thanks for help 😄
